org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
android.useAndroidX=true

GROUP=io.github.raheelnaz
VERSION_NAME=0.10.0

POM_DESCRIPTION=Android integration and testing for Molecule presenters.
POM_URL=https://github.com/raheelnaz/mauzun/
POM_SCM_URL=https://github.com/raheelnaz/mauzun/
POM_SCM_CONNECTION=scm:git:git://github.com/raheelnaz/mauzun.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/raheelnaz/mauzun.git

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit/
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=raheelnaz
POM_DEVELOPER_NAME=Raheel Naz

mavenCentralPublishing=true
signAllPublications=true
