name: build

on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

env:
  GRADLE_OPTS: "-Dkotlin.incremental=false -Dorg.gradle.logging.stacktrace=full"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew build

      - name: Publish test report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
          check_name: tests
          detailed_summary: true
          include_passed: true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: '**/build/reports/tests'
